### PR TITLE
Merge pathx branch with master

### PR DESCRIPTION
**Pull request by edawson**
I suggest that @guanmingwu 's pathx branch merges with master so that users reaching the repo see the latest source code (rather than the code I last touched four years ago). Github should handle the merge automatically, but it would be good to have tests to make sure no regressions occur.

Once the two are merged development can still happen on pathx while stable code can persist on the master branch. I'm happy to help with the merge and hand over ownership of the repo.

### CODE REVIEW

**Comment by alyst** [comment]
Keeping this git repo in sync with the actual plugin version would be really great.

**Comment by edawson** [comment]
Hey @alyst - do you just mean the merge of path-x into master, or are there other features in the plugin that aren't in the repo?

It's been years since I touched this repo, but I could reach out to @guanmingwu and see if what could be done.

**Comment by edawson** [comment]
I see. I'll reach out to Guanming. Let me know if there's any other way I can help!

**Comment by alyst** [comment]
@edawson Thanks a lot!

**Comment by guanmingwu** [comment]
The HotNet implementation actually is not in this codebase. It is in another server-side project, which has not been placed here. The implementation is for the original HotNet, which is outdates. I suggest you to take a look at our new HotNet2 implementation: https://github.com/melissayan/hotnet2-java. However, this HotNet2 has not been integrated into ReactomeFIViz because of the performance issue we have not figured out.

**Comment by alyst** [comment]
@guanmingwu Thanks for the info! Actually, HotNet2 integration is exactly what I'be been wondering about. If HotNet2 is resource-demanding, would it be possible to set up the server locally, and instruct ReactomeFIViz to communicate with the local server?

**Comment by guanmingwu** [comment]
Unfortunately the ReactomeFIViz code has not been switched to use HotNet2 yet. So it is not possible to use a local server serving HotNet2 for ReactomeFIViz.

**Pull request merged**
